// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0FwsBl4HrMsWIlW8iQvQe2Scrn50YmU',
    appId: '1:231231882700:web:4280d2c24edae59c938969',
    messagingSenderId: '231231882700',
    projectId: 'fabric-a8301',
    authDomain: 'fabric-a8301.firebaseapp.com',
    storageBucket: 'fabric-a8301.firebasestorage.app',
    measurementId: 'G-NHHZFQ4G53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_WbZozRqo8LQlSdKtysi0yr6m5KfMGQ',
    appId: '1:231231882700:android:1d72c9952e50940d938969',
    messagingSenderId: '231231882700',
    projectId: 'fabric-a8301',
    storageBucket: 'fabric-a8301.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpp2QaaklTAtAtwrkk64YDOUn-UaJ6fJI',
    appId: '1:231231882700:ios:42fe660910df326b938969',
    messagingSenderId: '231231882700',
    projectId: 'fabric-a8301',
    storageBucket: 'fabric-a8301.firebasestorage.app',
    iosBundleId: 'com.example.fabricAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpp2QaaklTAtAtwrkk64YDOUn-UaJ6fJI',
    appId: '1:231231882700:ios:42fe660910df326b938969',
    messagingSenderId: '231231882700',
    projectId: 'fabric-a8301',
    storageBucket: 'fabric-a8301.firebasestorage.app',
    iosBundleId: 'com.example.fabricAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0FwsBl4HrMsWIlW8iQvQe2Scrn50YmU',
    appId: '1:231231882700:web:60b6d794032f3234938969',
    messagingSenderId: '231231882700',
    projectId: 'fabric-a8301',
    authDomain: 'fabric-a8301.firebaseapp.com',
    storageBucket: 'fabric-a8301.firebasestorage.app',
    measurementId: 'G-S7NEP829L5',
  );
}
